import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { ToastContainer, Bounce } from "react-toastify";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={dm_sans.className}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light" />
            {children}
        <ToastContainer />
      </body>
    </html>
  );
}
